### PR TITLE
Fix InstantiationError when using any() where a sealed type is expected

### LINKED ISSUE #934: Mockk cannot handle sealed classes in `every` block
Sample project: https://github.com/ThanksForAllTheFish/mockk832
Related: https://github.com/mockk/mockk/issues/832

Mockk 1.13.2 still throws

```
org.t4atf.mockk832.Node
java.lang.InstantiationError: org.t4atf.mockk832.Node
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor17.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
	at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
	at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
```

when using sealed classes on kotlin 1.7 and java 17. The issue now is in `every` blocks, for instance:

```
class Root : Node()
class Leaf : Node()

interface Factory {
    fun create() : Node
    fun copy(node: Node) : Node
}

open class MyTest {
    @Test
    open fun aTest() {
        val mockk = mockk<Factory>()
        every { mockk.create() } returns Leaf() // this was fixed in mockk832

        println(mockk.create())

        every { mockk.copy(any()) } returns Root() //but this still breaks
    }
}
```

### PR DESCRIPTION
**Pull request by cliffred**
Fixes #934

There's no specific test for the issue, that is part of this pr: https://github.com/mockk/mockk/pull/937

### CODE REVIEW

**Review by josepanguera — APPROVED** [review]

**Comment by Raibaz** [comment]
Thanks for looking into this.

Can you also add test coverage, please? 🙏

**Comment by cliffred** [comment]
Done, @diastremskii already added tests for this is in his PR #937, I've merged that commit into my branch.

**Comment by ThanksForAllTheFish** [comment]
Are the failing test with java 19 what is holding back this PR?

**Comment by m-burst** [comment]
I guess it would help to rebase the PR onto the current master branch, as it uses Java 18 instead of 19 in the CI matrix

**Comment by pkgonan** [comment]
Any release plan about this PR?

**Comment by gotson** [comment]
Would really appreciate a release, now that Spring Boot 3.0.0 is GA, and targets Java 17, this is becoming a blocker for a migration.

**Comment by Raibaz** [comment]
You're right, just released v1.13.3: https://github.com/mockk/mockk/releases/tag/1.13.3

**Pull request merged**
