### PR TITLE
Inline mocked subclass of sealed class along with the sealed class itself

### LINKED ISSUE #938: Missing mocked calls exception for Sealed class
``` kotlin
val sealedClass = mockk<SealedClass>()
every { sealedClass.id } returns 0
```

### Expected Behavior

mockk for Sealed classes should work fine like on version 1.13.1

### Current Behavior

mockk for Sealed classes don't work

#### Context

* MockK version: 1.13.2
* OS: macOS Monterey 12.6
* Kotlin version: 1.7.10
* JDK version: JDK 11
* JUnit version: 4.13.2
* Type of test: unit test

#### Failure Logs

`io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock`

### LINKED ISSUE #978: MockKException: Failed matching mocking signature with mocked sealed type on 1.13.2
#### Steps to Reproduce

1. Mock sealed interface or class
2. Setup the created mock call using the `every { ... }` block (I used the `any()` matcher for argument)

#### Context

* MockK version: 1.13.2
* Kotlin version: 1.7.21
* JDK version: 11
* JUnit version: 5
* Type of test: unit test

#### Stack trace

```
io.mockk.MockKException: Failed matching mocking signature for

left matchers: [any()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)
...

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
import io.mockk.*
import org.junit.jupiter.api.Test
import kotlin.test.assertNotNull

sealed interface Sealed {
    abstract fun doSomething(arg: Any?)
}

class A : Sealed {
    override fun doSomething(arg: Any?) {}
}

class SealedClassTest {

    @Test
    fun test() {
        val a = mockk<Sealed>()

        every { a.doSomething(any()) } just Runs

        assertNotNull(a)
    }
}
```

### LINKED ISSUE #987: NullPointerException when mocking a sealed class on mockk 1.13.3
Hi, apologies if this is a duplicate, but the earlier issues with sealed classes on 1.13.2 and the 1.13.3 release have not fixed this example, and the exception is different to https://github.com/mockk/mockk/issues/978 even if it may be a related bug.

### Expected Behavior

Mocking a sealed class with a data class subclass to work.

#### Steps to Reproduce

The following test fails with a NullPointerException on the `every` line on mockk 1.13.2 and mockk 1.13.3 but not mockk 1.13.1

```kotlin
import io.mockk.every
import io.mockk.mockk
import io.junit.Test

sealed class Foo {
    data class Bar(
        val a: String,
    ): Foo()
}

interface FooPrinter {
    fun printFoo(foo: Foo)
}

class MockTest {
    @Test
    fun `test mock`() {
        val foo = mockk<Foo>()
        val printer = mockk<FooPrinter>()
        every { printer.printFoo(foo) } returns Unit
    }
}
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2 & 1.13.3
* Kotlin version: 1.7.10
* JDK version: 11
* JUnit version: 4
* Type of test: unit 

Also, if line `val a: String,` is replaced with `val a: Int` the test passes

#### Stack trace

```
java.lang.NullPointerException
    at com.example.mocktest.Foo$Bar.hashcode(MockTest.kt)
    at io.mockk.EqMatcher.hashCode(Matchers.kt)
    ...
```

### PR DESCRIPTION
**Pull request by m-burst**
Fixes #938, fixes #978, fixes #987

### CODE REVIEW

**Comment by Raibaz** [comment]
Nice one, thanks a lot for putting this together!

**Comment by m-burst** [comment]
@Raibaz Thanks for merging this! Do you think you'll be able to release this in a new patch version anytime soon?

**Comment by dhladik** [comment]
Could I also please ask if there's a release coming soon? I really wanted to update the project to Kotlin 1.7 but I've been upping the versions of `mockk` since 1.12.x

Thanks ❤️

**Comment by pkgonan** [comment]
@Raibaz Hi. Please release new version

**Comment by luongvo** [comment]
@Raibaz We really need to have new version soon, thanks 👍

**Comment by Raibaz** [comment]
Sorry for the delay, v1.13.4 is out now.

**Pull request merged**
