### PR TITLE
fix: fix value class field determination

### PR DESCRIPTION
**Pull request by qoomon**
To get value class property we need to find the one property with a backing field because value classes can have any number of properties without a backing field as well.

### CODE REVIEW

**Comment by aSemy** [comment]
Nice catch! LGTM

**Comment by Raibaz** [comment]
Nice, thanks!

**Comment by knyttl** [comment]
When will this be released?

**Comment by Raibaz** [comment]
Likely next week, I'm on vacation this week but I may find some time to publish a release.

**Comment by MarvinSchramm** [comment]
Enjoy your Vacation @Raibaz !

**Comment by monosoul** [comment]
Hey @Raibaz , sorry for pinging, but could you please release this? Thanks!

**Comment by Raibaz** [comment]
Sorry for the delay, just released v1.12.6: https://github.com/mockk/mockk/releases/tag/1.12.6

**Comment by knyttl** [comment]
For now I am getting:

```
      > Could not find io.mockk:mockk-jvm:1.12.6.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
          - https://jitpack.io/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
          - https://plugins.gradle.org/m2/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
```

**Comment by Raibaz** [comment]
It may take a while for the release to propagate on maven central.

Sorry about that, just retry in a while.

**Comment by aSemy** [comment]
`mockk-jvm-1.12.6.pom` is still not available, which is unusual. I'm very confused because the `.asc` signature and checksum files are available, so clearly it existed at some point.

https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/

image

**Comment by qoomon** [comment]
Actually it was published I'm already using it. See https://search.maven.org/artifact/io.mockk/mockk/1.12.6/jar

**Comment by aSemy** [comment]
@qoomon It's not working for me. Do you have 1.12.6 deployed to Maven Local?

**Comment by qoomon** [comment]
@aSemy you are right I've accidentally deployed a 1.12.6 version locally, my bad.

**Pull request merged**
