### PR TITLE
Java-12 compatibility

### PR DESCRIPTION
**Pull request by xiaodong-xie**

### CODE REVIEW

**Comment by xiaodong-xie** [comment]
This could reduce some incompatibles, but the issues we are facing are not fully resolved. We still got: 

```

Caused by: java.lang.IllegalArgumentException: io.mockk.renamed.java.util.concurrent.ExecutorService$Subclass21 must be defined in the same package as java.util.concurrent.ExecutorService/package

**Comment by xiaodong-xie** [comment]
This PR should be able to resolve exceptions like this one: 

```
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Cannot define nest member class java.lang.reflect.AccessibleObject$Cache + within different package then class net.bytebuddy.mirror.AccessibleObject

**Comment by xiaodong-xie** [comment]
Ping @oleksiyp, thanks.

**Comment by xiaodong-xie** [comment]
OK, I fixed 

```
Caused by: java.lang.IllegalArgumentException: io.mockk.renamed.java.util.concurrent.ExecutorService$Subclass21 must be defined in the same package as java.util.concurrent.ExecutorService/package

**Comment by xiaodong-xie** [comment]
Fixes https://github.com/mockk/mockk/issues/276

**Comment by oleksiyp** [comment]
Great, will be able to release today in the evening or  better on Sunday after bugfixing

**Comment by xiaodong-xie** [comment]
Cool, thanks a lot, @oleksiyp. 👍 😄

**Comment by xiaodong-xie** [comment]
Thanks for merging, @oleksiyp 👍 😄

**Pull request merged**
