### PR TITLE
run test(s) w/ current build

### PR DESCRIPTION
**Pull request by agebhar1**
I guess the tests ran with 1.8.8-SNAPSHOT :thinking:

### CODE REVIEW

**Comment by Raibaz** [comment]
The `matrix` folder is to manually generate a test matrix with different jdk versions.

I think it can safely be removed now that we have github actions to do the same thing.

**Comment by agebhar1** [comment]
I've updated the PR accordingly.

**Comment by Raibaz** [comment]
Thanks a lot!

**Comment by agebhar1** [comment]
My pleasure!

**Pull request merged**
