### PR TITLE
Introduce `verifyCount` DSL

### PR DESCRIPTION
**Pull request by T45K**
**this is draft implementation**
i'd like maintainers to check such points
- `API.kt` and `MockK.kt` are implemented appropriately
- tests are enough
- some changes i added as refactoring are acceptable

thank you

___

## Overview
based on [this discussion](https://github.com/mockk/mockk/discussions/1227), i added `verifyCount` DSL to make verifying call count easy

## Syntax
```
val mock = mockk<ClassUnderTest>()

...

verifyCount {
  1 * { mock.method() } // this is same as verify(exactly = 1) { mock.method() }
  0 * { mock.method() } // this is same as verify(exactly = 0) { mock.method() }
  (0..5) * { mock.method() } // this is same as verify(atLeast = 0, atMost = 5) { mock.method() }
}
```

this is inspired by [Spock](https://spockframework.org/spock/docs/2.3/spock_primer.html#_interactions) and [Mockito-Kotlin](https://github.com/mockito/mockito-kotlin/blob/main/mockito-kotlin/src/main/kotlin/org/mockito/kotlin/VerifyScope.kt#L44)

### CODE REVIEW

**Comment by Raibaz** [comment]
Overall LGTM, two observations:
- Can you please run the `:mockk-dsl:apiDump` gradle task to update the API definitions file?
- Would you also be able to add documentation for this in the README.md file?

Thanks a lot for putting this together, this looks really cool!

**Comment by T45K** [comment]
@Raibaz 
thank you for checking!
i updated where you pointed out.

could you check whether the doc is OK?

**Comment by T45K** [comment]
hmm, do i need something to do to pass all CI?

**Comment by T45K** [comment]
@Raibaz 
could you check again? 🙏

**Review by Raibaz — APPROVED** [review]

**Comment by Raibaz** [comment]
Looks great, thanks a lot! 🙏

**Pull request merged**
