### PR TITLE
fix: [#989] Slf4J and logback downgrade

### PR DESCRIPTION
**Pull request by Slava-Miligoulo-Target**
Lowered baseline slf4j and logback version for backward compatability.

### CODE REVIEW

**Review by desilvai-target — APPROVED** [review]
This will fix backward compatibility issues mentioned in comments for #989

**Comment by Raibaz** [comment]
I don't think we should depend on an unsupported version of SLF4J.

I'r dather keep depending on the latest version and have people exclude our own dependency they really want to depend on older ones.

**Comment by desilvai-target** [comment]
> I don't think we should depend on an unsupported version of SLF4J.
> 
> I'd rather keep depending on the latest version and have people exclude our own dependency they really want to depend on older ones.

That would be my preference too.  Just wasn't sure if the project objectives were around minimal changes for the user or staying somewhat current.

**Comment by Slava-Miligoulo-Target** [comment]
Works for us, going to close out this PR.

**Pull request closed without merging**
