### PR TITLE
Add andThenJust

### PR DESCRIPTION
**Pull request by NWuensche**

### CODE REVIEW

**Comment by Raibaz** [comment]
Thanks a lot for this, it was indeed missing from the DSL.

Can you just add it in the documentation as well plase?

A line in the table in the "Additional answer" section, mentioning that it will be available since v1.12.2, will be enough.

Thanks again!

**Comment by NWuensche** [comment]
Thank you! I added the documentation. Please tell me if there is anything else to do.

**Comment by Raibaz** [comment]
Awesome, thanks a lot!

**Comment by Raibaz** [comment]
Can you also make sure that the builds pass?

**Comment by NWuensche** [comment]
Hopefully everything works now :D

**Comment by Raibaz** [comment]
Thanks a lot!

**Pull request merged**
