### PR TITLE
Add `Awaits` extensions similar to `Runs` to await suspend functions until cancelled

### PR DESCRIPTION
**Pull request by SimonMarquis**
And adding kotlinCoroutinesTest dependency for testing purposes.

Examples:
```kotlin
coJustAwait { mock.coOp() }
coEvery { mock.coOp() } just awaits
coEvery { mock.coOp() } answers { 1 } andThenJust awaits
```

See discussion https://github.com/mockk/mockk/discussions/924

### CODE REVIEW

**Comment by SimonMarquis** [comment]
👋 Hi, not sure why this error happens.
It works fine on my local env, could this be a caching issue?


```
FAILURE: Build failed with an exception.

* Where:
Initialization script '/home/runner/.gradle/init.d/build-result-capture.init.gradle' line: 76

* What went wrong:
Could not open dsl generic class cache for script '/home/runner/.gradle/init.d/build-result-capture-service.plugin.groovy' (/home/runner/.gradle/caches/7.5.1/scripts/9y1w1goaggjti8kw09okbawrx).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
```
https://github.com/mockk/mockk/actions/runs/3160090370/jobs/5159103278#step:5:20

**Comment by SimonMarquis** [comment]
Latest Gradle 7.5.1 does not seem to be compatible with the newly released Java 19.
https://docs.gradle.org/current/userguide/compatibility.html

CI did not run completely on the commit upgrading Java version: https://github.com/mockk/mockk/commit/985c6feedce4372e0b5f64f74d6f82898b19d0a9

What should we do?
- Revert to Java 18 until Gradle officially supports it?
- Use an nightly Gradle version and see if it works?
- Ignore those errors until Gradle officially supports Java 19?

**Comment by Raibaz** [comment]
I'd remove support for java 19 until gradle supports it.

I think you can do it in this PR.

Thanks for looking into it!

**Comment by Raibaz** [comment]
Code LGTM, can you please just add an example usage of `just Awaits` and `coJustAwait` in the documentation in README.md?

**Comment by SimonMarquis** [comment]
@Raibaz tell me if the `coJustAwait` example is good enough.
Also, I've flagged these new APIs as `(available since v1.13.3)` but I'll let you decide for the new version name.

**Pull request merged**
