### PR TITLE
expose more mockk projects as API dependencies

### LINKED ISSUE #903: Missing transitive dependencies for Android tests
### Expected Behavior

Compilation should just work with the default gradle/maven setup:

```groovy
androidTestImplementation "io.mockk:mockk-android:1.12.7"
androidTestImplementation "io.mockk:mockk-agent-jvm:1.12.7"
```

Source: https://mockk.io/#gradlemaven-dependency

### Current Behavior

The public mockk dsl is not available for the `androidTest` configuration: `io.mockk.mockk`, `io.mockk.verify`

Though it is available for the regular `test` configuration when adding dependencies with `testImplementation`.

---

Here are the resolved dependencies: (I removed all non-mockk dependencies for clarity)

- `gradlew dependencies --configuration debugAndroidTestCompileClasspath`
  ```
  debugAndroidTestCompileClasspath - Compile classpath for compilation 'debugAndroidTest' (target  (androidJvm)).
  +--- io.mockk:mockk-android:1.12.7
  +--- io.mockk:mockk-agent-jvm:1.12.7
  |    +--- io.mockk:mockk-agent-api:1.12.7
  |         \--- io.mockk:mockk-agent-api-jvm:1.12.7
  +--- io.mockk:mockk-android:{strictly 1.12.7} -> 1.12.7 (c)
  +--- io.mockk:mockk-agent-jvm:{strictly 1.12.7} -> 1.12.7 (c)
  +--- io.mockk:mockk-agent-api:{strictly 1.12.7} -> 1.12.7 (c)
  \--- io.mockk:mockk-agent-api-jvm:{strictly 1.12.7} -> 1.12.7 (c)
  ```

- `gradlew dependencies --configuration debugAndroidTestRuntimeClasspath`
  ```
  debugAndroidTestRuntimeClasspath - Runtime classpath of compilation 'debugAndroidTest' (target  (androidJvm)).
  +--- io.mockk:mockk-android:1.12.7
  |    +--- io.mockk:mockk:1.12.7
  |    |    \--- io.mockk:mockk-jvm:1.12.7
  |    |         +--- io.mockk:mockk-dsl:1.12.7
  |    |         |    \--- io.mockk:mockk-dsl-jvm:1.12.7
  |    |         +--- io.mockk:mockk-agent:1.12.7
  |    |         |    \--- io.mockk:mockk-agent-jvm:1.12.7
  |    |         |         +--- io.mockk:mockk-agent-api:1.12.7
  |    |         |              \--- io.mockk:mockk-agent-api-jvm:1.12.7
  |    |         \--- io.mockk:mockk-agent-api:1.12.7 (*)
  |    +--- io.mockk:mockk-agent-api:1.12.7 (*)
  |    +--- io.mockk:mockk-agent-android:1.12.7
  |         +--- io.mockk:mockk-agent-api:1.12.7 (*)
  |         \--- io.mockk:mockk-agent:1.12.7 (*)
  \--- io.mockk:mockk-agent-jvm:1.12.7 (*)
  ```

---

It seems that the `io.mockk:mockk` artifact is not part of the compilation classpath, but only a runtime dependency.

### PR DESCRIPTION
**Pull request by aSemy**
fix #903

maybe helps #891 #889, so the `mockk-jvm` workaround isn't needed any more?

### CODE REVIEW

**Comment by aSemy** [comment]
Here's the dependencies in the `pom.xml` for `io.mockk:mockk`

```xml
  <dependencies>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-dsl</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-api</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.7.10</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

And for `io.mockk:mockk-android`

```xml

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jetbrains.kotlinx</groupId>
        <artifactId>kotlinx-coroutines-bom</artifactId>
        <version>1.6.4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-api</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-android</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.7.10</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

**Comment by Raibaz** [comment]
LGTM.

@SimonMarquis can you please try deploying this branch to your local maven repo and see if it fixes your issue?

**Comment by aSemy** [comment]
`io.mockk:mockk` looks correct compared to 1.12.5 https://repo.maven.apache.org/maven2/io/mockk/mockk/1.12.5/mockk-1.12.5.pom

I think it's a mistake that `kotlinx-coroutines` is exposed in `io.mockk:mockk-android`, that's a change from 1.12.5 https://repo.maven.apache.org/maven2/io/mockk/mockk-android/1.12.5/mockk-android-1.12.5.pom

**Comment by aSemy** [comment]
Removing the Coroutines dependencies from `mockk-android` seems to have fixed the `pom.xml`, now let's see if the tests still run...

```xml

  <dependencies>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-api</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-android</artifactId>
      <version>1.12.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.7.10</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

**Comment by SimonMarquis** [comment]
https://github.com/mockk/mockk/pull/905/commits/56b30de59ee221b487276abef43a93532a6dad9c works fine on my setup 👍

**Comment by SimonMarquis** [comment]
> `io.mockk:mockk` looks correct compared to 1.12.5 https://repo.maven.apache.org/maven2/io/mockk/mockk/1.12.5/mockk-1.12.5.pom

I think we never made the jump to this version because of missing `.so` shared libs at work.
In our setup, we only had a single dependency for pure jvm tests, and another one for android tests.

**Comment by SimonMarquis** [comment]
👋 Hi, is there any ETA for this fix to land in the 1.12.8?

**Comment by Raibaz** [comment]
Just released v1.12.8, sorry about the delay.

**Comment by SimonMarquis** [comment]
🚀 awesome thanks!

**Pull request merged**
