### PR TITLE
#854 update projects to use new Kotlin Multiplatform Gradle plugin

### PR DESCRIPTION
**Pull request by aSemy**
Initial steps at implementing #854, and migrating to the new Kotlin Multiplatform plugin. Additionally, re-organises the subprojects to a flatter structure.

- [x] share common Gradle config in buildSrc convention plugins
- [x] verify the `.api` files are the same. They're still generated, but each new subproject has a single merged file, so I didn't try comparing
- [x] re-enable Android projects. I'm not an Android developer, so I would like help with this.
- [x] re-enable dokka
- [x] re-enable Maven publishing
- [x] finish migrating `plugins/configuration` plugins to buildSrc plugins
- [ ] remove `modules/mockk-agent-api/api-old` files (I moved them here because the `mockk-agent-common` and `mockk-agent-api` projects were merged, and I wanted to make sure the new `.api` matched)
- [x] I wasn't sure what the purpose of `localrepo=/Users/raibaz/.m2/repository` in `gradle.properties`, so I didn't migrate it. @Raibaz Can this be replaced by running `./gradlew publishToMavenLocal`?
   UPDATE: changed to be system-independent, can be overridden on machines in `$GRADLE_USER_HOME/gradle.properties`
- [x] Verify that the new Gradle Toolchain config means the different JDKs are tested in the GitHub action matrix. Might need to parameterise this...

### Summary

- refactored projects to use newer Kotlin Multiplatform plugin
- New subprojects are
  - `mockk`
  - `mockk-agent`
  - `mockk-agent-android`
  - `mockk-agent-android-dispatcher`
  - `mockk-agent-api`
  - `mockk-android`
  - `mockk-dsl`
  
  the only significant difference is that `mockk-agent-common` was merged into `mockk-agent-api`. 
- grouped subprojects under 'modules' directory
- set up buildSrc convention plugins
- migrated all Gradle config to Kotlin
- Renamed `ValueClassSupport` to `ValueClassSupportAndroid` in the Android project (temp fix because I got an error - this should be fixed in #857)
- You can test publishing by running `./gradlew publishAllPublicationsToLocalRepoRepository` and seeing the result in `./build/maven-local-repo`
- removed Jacoco, and replaced it with [Kotlinx Kover](https://github.com/Kotlin/kotlinx-kover)
- Javadoc is now provided by Dokka HTML

### CODE REVIEW

**Comment by aSemy** [comment]
@Raibaz Hey, could you have a look at the progress so far? I'd like to know what you think before I finish up.

It would probably be easier to look at the changes by checking out the branch, then you can see the new structure.

A summary

* I haven't made any code changes - only build config
* updated projects to use Kotlin Multiplatform layout
* Created some convention plugins in buildSrc - the build config is a lot neater now!
* moved subprojects to `modules/` subdirectory, and flattened them so they're not nested (e.g. the `mockk-agent-android-dispatcher` project was nested inside `mockk-agent-android`). This helped during refactoring, so I knew which subprojects were refactored, and the un-refactored ones were still in the base project
* I wanted to tidy up the root directory, so I moved some of the media files into the `doc/` directory - this might break some links? I can revert it

**Comment by Raibaz** [comment]
Looks pretty cool so far, thanks a lot!

**Comment by aSemy** [comment]
okay, ready for review!

**Comment by Raibaz** [comment]
About the question in the initial comment on `localrepo`: i don't think it can be removed, it's not exactly the same as doing `publishToMavenLocal`.

It's meant to publish to a local repo that is not necessarily maven local, i.e. not necessarily `~/.m2/repository`,  to do a dry run of a local deployment without polluting maven local.

I'd keep it as it is for now.

**Comment by Raibaz** [comment]
Uhm, I can't seem to get this to build locally:

```
➜  mockk git:(fix/854-update-build-config) ✗ ./gradlew clean build --info
Initialized native services in: /Users/raibaz/.gradle/native
Initialized jansi services in: /Users/raibaz/.gradle/native
The client will now receive all logging from the daemon (pid: 12732). The daemon log file: /Users/raibaz/.gradle/daemon/7.5/daemon-12732.out.log
Starting 5th build in daemon [uptime: 7 mins 40.089 secs, performance: 100%, non-heap usage: 16% of 768 MiB]
Using 10 worker leases.
Now considering [/Users/raibaz/dev/mockk, /Users/raibaz/dev/mockk/buildSrc] as hierarchies to watch
Now considering [/Users/raibaz/dev/mockk/buildSrc, /Users/raibaz/dev/mockk] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
[android-sdk-detector] Android SDK detected: /Users/raibaz/Library/Android/sdk
Settings evaluated using settings file '/Users/raibaz/dev/mockk/settings.gradle.kts'.
Using local directory build cache for the root build (location = /Users/raibaz/.gradle/caches/build-cache-1, removeUnusedEntriesAfter = 7 days).
Type-safe project accessors is an incubating feature.
Skipping generation of project accessors as it is up-to-date.
Projects loaded. Root project using build file '/Users/raibaz/dev/mockk/build.gradle.kts'.
Included projects: [root project 'mockk-root', project ':modules', project ':modules:client-tests', project ':modules:mockk', project ':modules:mockk-agent', project ':modules:mockk-agent-android', project ':modules:mockk-agent-android-dispatcher', project ':modules:mockk-agent-api', project ':modules:mockk-android', project ':modules:mockk-dsl']
Skipping generation of project accessors as it is up-to-date.

> Configure project :buildSrc
Evaluating project ':buildSrc' using build file '/Users/raibaz/dev/mockk/buildSrc/build.gradle.kts'.
kotlin scripting plugin: created the scripting discovery configuration: kotlinScriptDef
kotlin scripting plugin: created the scripting discovery configuration: testKotlinScriptDef
file or directory '/Users/raibaz/dev/mockk/buildSrc/src/main/resources', not found
file or directory '/Users/raibaz/dev/mockk/buildSrc/src/main/java', not found
file or directory '/Users/raibaz/dev/mockk/buildSrc/src/main/groovy', not found
Build cache key for Kotlin DSL accessors for project ':buildSrc' is 1c27d002be1c7413f8fc87a147549a7d
Skipping Kotlin DSL accessors for project ':buildSrc' as it is up-to-date.
Task name matched 'build'
Selected primary task 'build' from project :
Starting process 'command '/usr/libexec/java_home''. Working directory: /Users/raibaz/.gradle/daemon/7.5 Command: /usr/libexec/java_home -V
Successfully started process 'command '/usr/libexec/java_home''
Resource missing. [HTTP GET: https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse]
Resource missing. [HTTP GET: https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse]

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':buildSrc:compileGroovy'.
> Could not resolve all dependencies for configuration ':buildSrc:compileClasspath'.
   > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching these requirements: {languageVersion=8, vendor=any, implementation=vendor-specific}
         > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
            > Could not read 'https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

What am I doing wrong?

**Comment by aSemy** [comment]
> `Unable to download toolchain`

Hmm weird. I guess you're on a M1 Mac? Maybe it's this issue https://github.com/gradle/gradle/issues/19874 What versions of Java do you have installed? You might have to try and install JDK8 manually, or change the buildscripts to use another version like 11

* https://github.com/mockk/mockk/pull/855/files#diff-7b5c40eb5522b5216cfe8c75612e579a8db0daee9ded80df9ce6a56e8361a962R42
* https://github.com/mockk/mockk/pull/855/files#diff-5c0978d9ac7decc3452b1404db1d76aeaa4147954d1be02df5c51db812f3cfadR17
* 

```kotlin
    jvmToolchain {
        (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of(11))
    }
```

**Comment by aSemy** [comment]
> About the question in the initial comment on `localrepo`: i don't think it can be removed, it's not exactly the same as doing `publishToMavenLocal`.
> 
> It's meant to publish to a local repo that is not necessarily maven local, i.e. not necessarily `~/.m2/repository`, to do a dry run of a local deployment without polluting maven local.
> 
> I'd keep it as it is for now.

Okay cool, can do! 

At the moment if you run `./gradlew publishAllPublicationsToLocalProjectDirRepository` it will publish to `./build/maven-internal`. 

If you want to publish to a non-project directory, how about this?

* I'll add `localrepo` back into `gradle.properties`, but set it to `./build/maven-local-repo`. 
* On your machine in `$GRADLE_USER_HOME/gradle.properties` set `localrepo=/path/to/your/personal/.m2`

I'd like to keep the project settings independent of machine-specific config.

**Comment by aSemy** [comment]
Actually thinking about it, the new Gradle toolchain config means on ci/cd Gradle will always download JDK8, so the JDKs that are set in the GitHub action matrix aren't tested. I'll investigate.

**Comment by Raibaz** [comment]
> * I'll add `localrepo` back into `gradle.properties`, but set it to `./build/maven-local-repo`.
> * On your machine in `$GRADLE_USER_HOME/gradle.properties` set `localrepo=/path/to/your/personal/.m2`. This will override the project setting ([the order is documented here](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)).
> 
> This way, you can override the default, but the project has settings that work for everyone. I'd like to keep the project settings independent of machine-specific config.

Sure, this males a lot of sense, thanks!

**Comment by Raibaz** [comment]
Still cannot build it locally btw, getting the same error.

**Comment by aSemy** [comment]
> Still cannot build it locally btw, getting the same error.

Are you on an M1 Mac? Is it this issue? https://github.com/gradle/gradle/issues/19874

**Comment by Raibaz** [comment]
Yep that looks exactly like my case.

**Comment by aSemy** [comment]
I changed the buildSrc Toolchain to be jdk11 - that might fix it?

**Comment by Raibaz** [comment]
Yep this fixed it, thanks a lot!

**Pull request merged**
