### PR TITLE
try reverting Android minSdk to 21

### LINKED ISSUE #893: Update to 1.12.7 bumps `minSdkVersion` to 26 on Android
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Upgrade to 1.12.7 from 1.12.5 in a project with `minSdk 23`, everything keeps working. I would expect no breaking changes due to this being a patch release.

### Current Behavior

Test build fails due to incompatible `minSdk`. See stacktrace.

#### Steps to Reproduce

1. Create an Android project with `minSdk = 23`
2. Use mockK 1.12.7

#### Context

* MockK version: 1.12.7
* OS: Linux
* Kotlin version: 1.6.21
* JDK version: 11.0.13
* JUnit version: 4.13.2
* Type of test: unit test OR android instrumented test: both

#### Stack trace

```
* What went wrong:
Execution failed for task ':app:processGenericDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 26 declared in library [io.mockk:mockk-android:1.12.7] /home/user/.gradle/caches/transforms-3/0debc4558cb38f69fc40c4cac52d713c/transformed/jetified-mockk-android-1.12.7/AndroidManifest.xml as the library might be using APIs not available in 23
        Suggestion: use a compatible library with a minSdk of at most 23,
                or increase this project's minSdk version to at least 26,
                or use tools:overrideLibrary="io.mockk" to force usage (may lead to runtime failures)
```

### PR DESCRIPTION
**Pull request by aSemy**
Might resolve #893.

Changing minSdk was done in PR #863 , which was a modified PR based on #829. I don't know if the minSdk is required to be 26 - it doesn't seem like 23 has any problems.

### CODE REVIEW

**Comment by Raibaz** [comment]
Can you try setting `minSdkVersion` to 21 for additional backwards compatibility?

**Comment by SimonMarquis** [comment]
There are no compilation errors/warnings on my end when downgrading to `minSdk = 21` 👍

**Comment by SimonMarquis** [comment]
My bad, there is at least one: `Cast from ArraySet to Set requires API level 23 (current min is 21)` for

https://github.com/mockk/mockk/blob/fe36b92f89434f81fab2ef51cd8def5d2841ee14/modules/mockk-agent-android/src/main/java/io/mockk/proxy/android/AndroidMockKMap.java#L203

and

https://github.com/mockk/mockk/blob/fe36b92f89434f81fab2ef51cd8def5d2841ee14/modules/mockk-agent-android/src/main/java/io/mockk/proxy/android/AndroidMockKMap.java#L234-L235

**Comment by aSemy** [comment]
In this case the warnings aren't a problem :)

**Pull request merged**
