### PR TITLE
Update Kotlin & Coroutine version to 1.3.0 and 1.0.0 stable respectively

### PR DESCRIPTION
**Pull request by BoxResin**

### CODE REVIEW

**Comment by oleksiyp** [comment]
Have you tested that it is working well with this versions? Can I just release it?

**Comment by oleksiyp** [comment]
@BoxResin can you please check that version "1.8.10.kotlin13" is working well with Kotlin 1.3. for you?

**Comment by BoxResin** [comment]
Ok, I will check it.

2018년 10월 31일 (수) 오전 7:51, Oleksiy Pylypenko <notifications@github.com>님이
작성:

**Comment by BoxResin** [comment]
@oleksiyp It works perfectly. Thank you 👍

**Pull request merged**
