### PR TITLE
Kotlin1331

### PR DESCRIPTION
**Pull request by saschpe**
Update to Kotlin 1.3.31 and Coroutines 1.2.1

The Gradle plugin and library dependencies should match, thus remove
separate kotlin_gradle_version field in Gradle files.

Related to issues #151 and #193.

### CODE REVIEW

**Comment by saschpe** [comment]
The second commit only touches a few optimizations and style improvements. There's much more possible but I wanted to have a discussion first on what you consider appropriate.

**Comment by oleksiyp** [comment]
Isn't `kotlin13` branch is something you are looking for?

**Comment by saschpe** [comment]
You meant I should submit against it instead? It's otherwise empty, no?

**Comment by oleksiyp** [comment]
What I see is that you convert here from experimental coroutines to regular. Which make big sense as it is already done in `kotlin13` branch.

**Comment by saschpe** [comment]
Ok, I can put those changes on top of `kotlin13`, that branch uses an RC of an obsolete 1.3 version and depends on the EAP maven repo and seems to need a rebase as well ;-)

**Comment by oleksiyp** [comment]
It is more trickier than that :smile: You basically will need to split your changes to things end up in both branches and one for kotlin13.

**Pull request closed without merging**
