### PR TITLE
Adding throwsMany exception

### PR DESCRIPTION
**Pull request by daniel-dios**
Hi team! 😬🤓
This is @antonio-manuel and @daniel-dios from @N26!

Since we are testing Kafka ErrorHandlers we wanted to stub a method to return 10 times a given exception and then success with this amazing library 🙌

We are proposing this two new methods to make test even clearer!

Thanks a lot
💓

### CODE REVIEW

**Review by sergiocostaN26 — APPROVED** [review]

**Comment by Raibaz** [comment]
LGTM

Can you please also add documentation for this in the README.md file?

Thanks!

**Comment by antonio-manuel** [comment]
> LGTM
> 
> Can you please also add documentation for this in the README.md file?
> 
> Thanks!

Hey, thanks for your comment, we just updated the documentation. 

We noticed we had to update the mockk-dsl.api, but we didn't found in the documentation any reference to this file, what is the purpose of it? Should it be included in the CONTRIBUTION file?

**Comment by daniel-dios** [comment]
ping @Raibaz 👼

**Comment by daniel-dios** [comment]
ping @Raibaz 👼

**Comment by daniel-dios** [comment]
ping @Raibaz 👼

**Pull request merged**
