### PR TITLE
fix reading return type for suspending function returning generic type

### PR DESCRIPTION
**Pull request by hrach**
The previous #641 implemetnation was buggy, a fix here.

### CODE REVIEW

**Comment by hrach** [comment]
Finally I was able to obtains the stack trace:
```
java.lang.ClassNotFoundException: Invalid name: java.lang.Boolean[]
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:454)
at java.lang.Class.forName(Class.java:379)
at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:35)
at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
at io.mockk.MockKDsl.internalEvery(API.kt:93)
at io.mockk.MockKKt.every(MockK.kt:98)
at io.mockk.it.ArraysTest.booleanObjectArray(ArraysTest.kt:94)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

**Comment by hrach** [comment]
@Raibaz please don't you have idea what may be the cause here? Or any idea how to debug this? Thx

**Comment by hrach** [comment]
The issue is that from some reason Android isn't able to handle `kotlin.BooleanArray` and only works when the return type resolution returns `kotlin.Array`. I'm totally lost what this affects and how to properly fix it. Any idea please @Raibaz?

I've added a nasty fix 😢. Not sure how else to fix it. We may introduce some expect/actual but not sure it worth.  Mainly because the fix should be probably elsewhere.

**Comment by Raibaz** [comment]
I've seen the Android failures, and I honestly have no idea why it's failing :(

I'm not familiar enough with the Android ecosystem to have a clue about it.

BTW, looks like now there are failures in the JVM module as well.

Thanks for looking through this though!

**Comment by hrach** [comment]
This JVM failure was due to need to unbox value class after merging their support. So 🤞 fixed now.

**Comment by hrach** [comment]
> This JVM failure was due to need to unbox value class after merging their support.

And that's needed because now we read the return type by kotlin reflection and not throguh java reflection which already had the boxed type.

**Comment by Raibaz** [comment]
Great, thanks a lot for fixing everything!

**Pull request merged**
