### PR TITLE
fix: handle isValue exceptions

### PR DESCRIPTION
**Pull request by qoomon**

### CODE REVIEW

**Comment by Raibaz** [comment]
Not a big fan of catching `Throwable`.

Can we provide explicit casts for each exception type?

**Comment by qoomon** [comment]
I'm not either :-), however the known exceptions, that need to be catched are `kotlin. UnsupportedOperationException`  and`kotlin.reflect.jvm.internal.KotlinReflectionInternalError`. Unfortunately `KotlinReflectionInternalError` is an internal `Error`. Technically I want to catch Exceptions and Errors, but that is Throwable in the end :-(

**Comment by qoomon** [comment]
If it is okay I could catch `kotlin.reflect.jvm.internal.KotlinReflectionInternalError` and `UnsupportedOperationException` just for the jvm package and keep the other catch blocks as they are, just catching `UnsupportedOperationException`

**Comment by Raibaz** [comment]
Yep this looks much better, thanks!

**Pull request merged**
